import django
import os
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager

os.environ['DJANGO_SETTINGS_MODULE'] = 'tropics.settings'
django.setup()

from sands.models import Sand

courses = [
"English 9,English",
"English 10,English",
"AP English Language,English",
"AP English Language W/AP US Government (Global Studies),English",
"English 11 W/AP US History,English",
"English 11 W/US History,English",
"English 12,English",
"AP English Literature,English",
"AP English Literature W/ AP US Government (Senior Seminar),English",
"Broadcast Journalism 1,English",
"Broadcast Journalism 2,English",
"Broadcast Journalism 3,English",
"Broadcast Journalism 4,English",
"Forensics,English",
"Film Study,English",
"Journalism 1,English",
"Journalism 2,English",
"Journalism 3,English",
"Journalism 4,English",
"Photojournalism 1,English",
"Photojournalism 2,English",
"Photojournalism 3,English",
"Photojournalism 4,English",
"Band,Music",
"Percussion Ensemble,Music",
"Jazz Ensemble,Music",
"Orchestra,Music",
"Beginning Chorus,Music",
"AP Music Theory,Music",
"Technology Theatre 1,Theatre Arts",
"Theatre Arts 1 Sem,Theatre Arts",
"Theatre Arts 2 Sem,Theatre Arts",
"Theatre Arts 3 Sem,Theatre Arts",
"Technology Theatre 1 Sem,Theatre Arts",
"Theatre Arts 4 Sem,Theatre Arts",
"Digital Art 1,Visual Arts",
"Digital Art 2,Visual Arts",
"Studio Art & Design 3,Visual Arts",
"Studio Art/Design 4 P/P,Visual Arts",
"AP Art: 2-D Design,Visual Arts",
"AP Art: Drawing,Visual Arts",
"AP: Art History,Visual Arts",
"Studio Art & Design 1,Visual Arts",
"Studio Art & Design 2,Visual Arts",
"Photography 1,Visual Arts",
"Photography 2,Visual Arts",
"Self EPF Online,General",
"Economics Personal Finance,General",
"Economics Personal Finance Hn,General",
"Engineer Research,General",
"Intro Engineering Accelerated Advanced,General",
"Design And Technology,General",
"Audio Electronics,General",
"Advanced Microproc Systems,General",
"Micro Electronics Research,General",
"Accelerated Analog Electronics,General",
"Accelerated Digital Electronics,General",
"Autonomous/Robotics-Micro Systems,General",
"Autonomous/Robotics-Systems,General",
"Prototype Development 1,General",
"Spec Computer Assisted Design,General",
"Prototype Development 2,General",
"Energy Systems 2,General",
"Energy Systems 1,General",
"Engineering Design,General",
"Teachers For Tomorrow 1,General",
"Health And PE 9,Health & Physical Education",
"Health And PE 10,Health & Physical Education",
"Personal Fitness 1,Health & Physical Education",
"Yoga For Wellness,Health & Physical Education",
"Sports Medicine,Health & Physical Education",
"TJ Math 4,Mathematics",
"TJ Research Statistics 1,Mathematics",
"TJ Math 1,Mathematics",
"TJ Math 2,Mathematics",
"TJ Math 3,Mathematics",
"Data Structures,Computer Science",
"TJ Math 5,Mathematics",
"AP Calculus AB,Mathematics",
"TJ Math 6,Mathematics",
"AP Calculus BC,Mathematics",
"Multivariable Calculus,Mathematics",
"Linear Algebra,Mathematics",
"Differential Equations,Mathematics",
"Foundations Computer Science,Computer Science",
"Foundations Computer Science Accelerated,Mathematics",
"Machine Learning 1,Computer Science",
"Machine Learning 2,Computer Science",
"TJ Research Statistics 3,Mathematics",
"Advanced Mathematical Techniques,Mathematics",
"Computer Vision 2,Computer Science",
"TJ Research Statistics 2,Mathematics",
"Complex Analysis,Mathematics",
"Computer Vision 1,Mathematics",
"Artifical Intelligence 1,Computer Science",
"Artifical Intelligence 2,Computer Science",
"Computer Systems Research,Computer Science",
"Web App Development,Computer Science",
"Mobile App Development,Computer Science",
"Mobile/Web App Research,Computer Science",
"Biology 1,Science",
"AP Biology,Science",
"Chemistry 1,Science",
"AP Chemistry,Science",
"Geosystems,Science",
"Geospatialanalysis,Science",
"Physics 1,Science",
"AP Physics C-MEM,Science",
"Microbial Genomics,Science",
"Astronomy Mentorship,Science",
"Geosystems Mentorship,Science",
"Advanced Marine Biology,Science",
"Biotech Research,Science",
"Neuroscience Research,Science",
"DNA Science 1,Science",
"DNA Science 2,Science",
"Neurobiology,Science",
"Chemistry Analysis Research,Science",
"Intro Organic Chemistry 1,Science",
"Astronomy Research,Science",
"Advanced Astronomy Solar Systems,Science",
"Advanced Astronomy Universe,Science",
"Computational Physics,Science",
"Optics Research,Science",
"Optical Systems,Science",
"Electrodynamics,Science",
"Oceanography Research,Science",
"Bionanotechnology,Science",
"World History/Geography 1,Social Studies",
"AP US Government W/AP English Language (Global Studies),Social Studies",
"World History/Geography 2,Social Studies",
"AP US History,Social Studies",
"US VA History,Social Studies",
"AP US Government,Social Studies",
"AP US Government W/AP English Literature (Senior Seminar),Social Studies",
"African American History,Social Studies",
"AP European History,Social Studies",
"AP Macro/Micro Economics,Social Studies",
"AP Psychology,Social Studies",
"Ethical Leadership,Social Studies",
"Ancient & Classical Civilizations,Social Studies",
"20th Century World History,Social Studies",
"Psych: Brain & Behavior,Social Studies",
"Inquiry Into Ideas,Social Studies",
"Religious Studies,Social Studies",
"Anthropology Studies,Social Studies",
"History Of Science,Social Studies",
"America/World Since 1989,Social Studies",
"Law And Society,Social Studies",
"Chinese 1,World Languages",
"Chinese 2,World Languages",
"Chinese 3,World Languages",
"Chinese 4,World Languages",
"Chinese 5,World Languages",
"AP Chinese Language,World Languages",
"French 1,World Languages",
"French 2,World Languages",
"French 3,World Languages",
"French 4,World Languages",
"French 5,World Languages",
"AP French Language,World Languages",
"German 1,World Languages",
"German 2,World Languages",
"German 3,World Languages",
"German 4,World Languages",
"German 5,World Languages",
"AP German Language,World Languages",
"Japanese 2,World Languages",
"Japanese 3,World Languages",
"Japanese 4,World Languages",
"Japanese 5,World Languages",
"AP Japanese Language,World Languages",
"Latin 1,World Languages",
"Latin 2,World Languages",
"Latin 3,World Languages",
"Latin 4,World Languages",
"Latin 5,World Languages",
"AP Latin,World Languages",
"Spanish 1,World Languages",
"Spanish 2,World Languages",
"Spanish 3,World Languages",
"Spanish 4,World Languages",
"Spanish 5,World Languages",
"AP Spanish Language,World Languages",
"AP Spanish Literature,World Languages",
"Russian 1,World Languages",
"Russian 2,World Languages",
"Russian 3,World Languages",
"Russian 4,World Languages",
"Russian 5,World Languages",
"AP Russian Language,World Languages"
]

for course in courses:
    course_name, course_tag = course.split(",")[0], course.split(",")[1]
    sand = Sand(name=course_name, category=course_tag)
    sand.save()