# Generated by Django 4.0.6 on 2022-07-28 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now_add=True)),
                ('mangoes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waters', to=settings.AUTH_USER_MODEL)),
                ('sand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waters', to='sands.sand')),
            ],
            options={
                'ordering': ('-mangoes', 'date_added'),
            },
        ),
    ]
