# Generated by Django 4.0.6 on 2022-07-29 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='water',
            name='content',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(25, 'The field must contain at least 25 characters.')]),
        ),
    ]
