# Generated by Django 4.0.6 on 2022-08-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waters', '0002_alter_water_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='water',
            name='date_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
