# Generated by Django 4.0.6 on 2022-08-02 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waters', '0003_alter_water_date_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='water',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
