# Generated by Django 4.0.6 on 2022-08-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waters', '0004_water_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='water',
            name='date_edited',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
