# Generated by Django 4.0.6 on 2022-08-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waters', '0003_alter_water_date_edited'),
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gave_mangoes',
            field=models.ManyToManyField(blank=True, null=True, to='waters.water'),
        ),
    ]
