# Generated by Django 4.0.6 on 2022-08-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waters', '0003_alter_water_date_edited'),
        ('authentication', '0003_alter_user_gave_mangoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gave_mangoes',
            field=models.ManyToManyField(to='waters.water'),
        ),
    ]
