# Generated by Django 4.0.6 on 2022-08-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waters', '0004_water_deleted'),
        ('authentication', '0004_alter_user_gave_mangoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gave_mangoes',
            field=models.ManyToManyField(blank=True, to='waters.water'),
        ),
    ]
