# Generated by Django 4.0.6 on 2022-07-29 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 29, 8, 25, 32, 814230)),
        ),
    ]
