# Generated by Django 4.0.6 on 2022-07-29 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sands', '0002_alter_sandview_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sand',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sand',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sandview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 29, 10, 32, 41, 479620)),
        ),
    ]
