# Generated by Django 4.0.6 on 2022-07-29 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sands', '0004_alter_sand_slug_alter_sandview_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 29, 15, 1, 46, 748214)),
        ),
    ]
