# Generated by Django 4.0.6 on 2022-07-30 18:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sands', '0007_alter_sandview_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 30, 14, 1, 23, 278820)),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('fcps_email', models.EmailField(max_length=100)),
                ('sand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sandteachers', to='sands.sand')),
            ],
        ),
    ]
