# Generated by Django 4.0.6 on 2022-07-30 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sands', '0009_remove_sandview_created_remove_sandview_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='SandTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('fcps_email', models.EmailField(max_length=100)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_teachers', to=settings.AUTH_USER_MODEL)),
                ('sand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='sands.sand')),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
