# Generated by Django 4.0.6 on 2022-07-30 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sands', '0011_alter_sandteacher_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandteacher',
            name='fcps_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
