# Generated by Django 4.0.6 on 2022-08-01 02:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sands', '0012_alter_sandteacher_fcps_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandteacher',
            name='display_name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(5, 'The field must contain at least 5 characters.')]),
        ),
    ]
